.TH "dirs" 1 "Sun Nov 26 2017" "Version 2.7.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dirsdirs - print directory stack 
 \- 
.PP
.SS "Synopsis"
.PP
.nf

\fBdirs\fP
\fBdirs\fP -c
.fi
.PP
.SS "Description"
\fCdirs\fP prints the current directory stack, as created by the \fC\fCpushd\fP\fP command\&.
.PP
With '-c', it clears the directory stack instead\&.
.PP
\fCdirs\fP does not accept any parameters\&. 
