.TH "fish_update_completions" 1 "Sun Nov 26 2017" "Version 2.7.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fish_update_completionsfish_update_completions - Update completions using manual pages 
 \- 
.PP
.SS "Description"
\fCfish_update_completions\fP parses manual pages installed on the system, and attempts to create completion files in the \fCfish\fP configuration directory\&.
.PP
This does not overwrite custom completions\&.
.PP
There are no parameters for \fCfish_update_completions\fP\&. 
