.TH "pwd" 1 "Sun Nov 26 2017" "Version 2.7.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pwdpwd - output the current working directory 
 \- 
.PP
.SS "Synopsis"
.PP
.nf

\fBpwd\fP
.fi
.PP
.SS "Description"
\fCpwd\fP outputs (prints) the current working directory\&.
.PP
Note that \fCfish\fP always resolves symbolic links in the current directory path\&. 
